AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: (fiap-feedback-notifier) - Notificação de Feedback Crítico (MS2)

Parameters:
  SenderEmail:
    Type: String
    Description: "O endereço de e-mail verificado no SES para enviar as notificações."
    Default: "suaconta@gmail.com" # Seu email para testes

Globals:
  Function:
    Runtime: java17
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64

Resources:

  ## =========================
  ## Lambda - Urgency Notification Worker
  ## =========================
  UrgencyNotificationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ms2-urgency-notification-worker
      Runtime: java17
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
      CodeUri: target/function.zip

      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: urgencyNotificationWorker
          SENDER_EMAIL: !Ref SenderEmail
          # Importa o nome da tabela DynamoDB da stack compartilhada
          ADMIN_TABLE_NAME: !ImportValue AdminTableName

      Policies:
        - SQSPollerPolicy: # Permite ler do SQS (usando o nome da fila, que o SAM resolve se estiver na mesma conta/região)
            QueueName: FilaUrgencia
            
        - Statement: # Permissão SES para enviar e-mail
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"

        - Statement: # Permissão DynamoDB para ler inscritos
            Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !ImportValue AdminTableArn

      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            # Importa o ARN da fila SQS da stack compartilhada
            Queue: !ImportValue FilaUrgenciaArn
            BatchSize: 10


  ## =========================
  ## Lambda - Report Notification Worker
  ## =========================
  ReportNotificationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ms2-report-notification-worker
      Runtime: java17
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
      CodeUri: target/function.zip

      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: reportNotificationWorker
          SENDER_EMAIL: !Ref SenderEmail
          # Importa o nome da tabela DynamoDB da stack compartilhada
          ADMIN_TABLE_NAME: !ImportValue AdminTableName

      Policies:
        - Statement: # Permissão SES para enviar e-mail
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"

        - Statement: # Permissão S3 para baixar relatórios
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"

        - Statement: # Permissão DynamoDB para ler inscritos
            Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !ImportValue AdminTableArn

      Events:
        ReportSNSTrigger:
          Type: SNS
          Properties:
            Topic: !ImportValue ReportTopicArn

  ## =================================
  ## SES - Identidade de E-mail
  ## =================================
  SenderEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref SenderEmail
