AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: (fiap-feedback-notifier) - Notificação de Feedback Crítico (MS2)

Parameters:
  SenderEmail:
    Type: String
    Description: "O endereço de e-mail verificado no SES para enviar as notificações."
    Default: "emmanuellaf.albuquerque@gmail.com"

Globals:
  Function:
    Runtime: java17
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64

Resources:

  ## =========================
  ## SNS - Tópico de Urgência
  ## =========================
  UrgencyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Urgencia

  ## =========================
  ## Lambda - Notification Worker
  ## =========================
  NotificationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ms2-notification-worker
      Runtime: java17
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
      CodeUri: target/function.zip

      Environment:
        Variables:
          URGENT_TOPIC_ARN: !Ref UrgencyTopic
          SENDER_EMAIL: !Ref SenderEmail # Passa o e-mail para a Lambda

      Policies:
        - SNSPublishMessagePolicy: # Permite publicar no SNS
            TopicName: Urgencia
        - SQSPollerPolicy: # Permite ler do SQS
            QueueName: FilaUrgencia
        - Statement: # Permissões manuais para SNS (Listar) e SES (Enviar)
            Effect: Allow
            Action:
              - sns:ListSubscriptionsByTopic
            Resource: !Ref UrgencyTopic
        - Statement: # Permissão SES mais ampla para evitar erro de autorização no destino
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"

      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !ImportValue FilaUrgenciaArn
            BatchSize: 10

  ## =================================
  ## SES - Identidade de E-mail
  ## =================================
  SenderEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref SenderEmail
